### ISSUE TITLE
How should IE10 be handled?

### ISSUE THREAD

**Issue by wimpyprogrammer** [trevorreeves/superagent-legacyIESupport#3]
Thanks for this great superagent plugin!

I had trouble getting a CORS POST to work in IE10 until I disabled this plugin.  No `Content-Type` was sent so the server errored with `415 Unsupported Media Type`.  I started looking through the plugin code to investigate.

I see several mentions of shimming IE8 and IE9, but is this plugin also meant to affect IE10?  That version [seems to support CORS with `XMLHttpRequest`](http://blogs.msdn.com/b/ie/archive/2012/02/09/cors-for-xhr-in-ie10.aspx).

| Browser/OS | `"withCredentials" in (new XMLHttpRequest())` |
| --- | :-: |
| IE 8 / Win7 | :x: |
| IE 9 / Win7 | :x: |
| IE 10 / Win7 | :white_check_mark: |
| IE 10 / Win8 | :white_check_mark: |
| IE 11 / Win7 | :white_check_mark: |

Should the check for `typeof XDomainRequest !== "undefined"` be amended to `typeof XDomainRequest !== "undefined" && !("withCredentials" in (new XMLHttpRequest()))` ?

**Comment by trreeves** [comment]
Thanks @wimpyprogrammer for you input on this.  Big apologies that I haven't seen this until now (I need to review my Github email alerts!)
